//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myriad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieActor
    {
        public int RelID { get; set; }
        public int ActID { get; set; }
        public int MovID { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
