//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myriad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.MovieActors = new HashSet<MovieActor>();
        }
    
        public int MovID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Plot { get; set; }
        public string Poster { get; set; }
        public Nullable<int> ProID { get; set; }
    
        public virtual Producer Producer { get; set; }
        public virtual ICollection<MovieActor> MovieActors { get; set; }
    }
}
