//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myriad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        public Producer()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int ProID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Bio { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
